### ISSUE TITLE
c,d,e,f fails!

### ISSUE THREAD

**Issue by donavon** [bdchauvette/isogram.me#4]
The following code fails. 'e' is re-used in `var e=d.scripts[0]`.

```js
<script>
!function(c,d,e,f){c.GoogleAnalyticsObject=e;c[e]||(c[e]=function(){
(c[e].q=c[e].q||[]).push(arguments)});c[e].l=+new Date;f=d.createElement('script');
var e=d.scripts[0];f.src='//www.google-analytics.com/analytics.js';
e.parentNode.insertBefore(f,e)}(window,document,'ga');

ga('create', 'UA-XXXXX-X', 'auto');
ga('send', 'pageview');
</script>
```

**Comment by bdchauvette** [comment]
Good catch, thanks!

Looks like this is a bug in the [upstream code generating library](https://github.com/shinnn/isogram) (see e.g. https://runkit.com/embed/nacfwliritlh).

I'll open up an issue there later today after I've poked around the code a bit, and see if I can get a fix for it later this week 👍

**Comment by bdchauvette** [comment]
So after playing around with this a bit, and stepping through the snippet in the debugger, I can't seem to get it to fail.

I put together [a JS Bin](http://jsbin.com/suneverore/edit?html,js,console) to see if the isogram snippet is attaching the GA script to the `<head>`, and it seems to be working fine for me.

Could provide some more info about how the snippet is failing for you? Is it broken in a particular browser, or in a particular environment?

Thanks!
